//! エラーコード定数が draft-ietf-moq-transport-21 §16.11 の IANA レジストリ表と一致することのテスト

use shiguredo_moqt::error::{
    PUBLISH_DONE_EXCESSIVE_LOAD, PUBLISH_DONE_EXPIRED, PUBLISH_DONE_GOING_AWAY,
    PUBLISH_DONE_INTERNAL_ERROR, PUBLISH_DONE_MALFORMED_TRACK, PUBLISH_DONE_TOO_FAR_BEHIND,
    PUBLISH_DONE_TRACK_ENDED, PUBLISH_DONE_UNAUTHORIZED, PUBLISH_DONE_UPDATE_FAILED,
    REQUEST_CONFLICTING_FILTERS, REQUEST_DOES_NOT_EXIST, REQUEST_EXCESSIVE_LOAD,
    REQUEST_EXPIRED_AUTH_TOKEN, REQUEST_GOING_AWAY, REQUEST_INTERNAL_ERROR, REQUEST_INVALID_FILTER,
    REQUEST_INVALID_RANGE, REQUEST_MALFORMED_AUTH_TOKEN, REQUEST_MALFORMED_TRACK,
    REQUEST_NAMESPACE_TOO_LARGE, REQUEST_NOT_SUPPORTED, REQUEST_PREFIX_OVERLAP, REQUEST_REDIRECT,
    REQUEST_TIMEOUT, REQUEST_UNAUTHORIZED, REQUEST_UNINTERESTED, REQUEST_UNSUPPORTED_EXTENSION,
    SESSION_AUTH_TOKEN_CACHE_OVERFLOW, SESSION_CONTROL_MESSAGE_TIMEOUT,
    SESSION_DATA_STREAM_TIMEOUT, SESSION_DUPLICATE_AUTH_TOKEN_ALIAS, SESSION_DUPLICATE_TRACK_ALIAS,
    SESSION_EXPIRED_AUTH_TOKEN, SESSION_GOAWAY_TIMEOUT, SESSION_INTERNAL_ERROR,
    SESSION_INVALID_AUTHORITY, SESSION_INVALID_PATH, SESSION_INVALID_REQUEST_ID,
    SESSION_KEY_VALUE_FORMATTING_ERROR, SESSION_MALFORMED_AUTH_TOKEN, SESSION_MALFORMED_AUTHORITY,
    SESSION_MALFORMED_PATH, SESSION_NO_ERROR, SESSION_PROTOCOL_VIOLATION,
    SESSION_TOO_MANY_REQUEST_UPDATES, SESSION_UNAUTHORIZED, SESSION_UNKNOWN_AUTH_TOKEN_ALIAS,
    STREAM_CANCELLED, STREAM_DELIVERY_TIMEOUT, STREAM_EXCESSIVE_LOAD, STREAM_EXPIRED_AUTH_TOKEN,
    STREAM_GOING_AWAY, STREAM_INTERNAL_ERROR, STREAM_MALFORMED_TRACK, STREAM_SESSION_CLOSED,
    STREAM_TOO_FAR_BEHIND, STREAM_UNKNOWN_OBJECT_STATUS,
};

/// §16.11.1 (Session Termination Error Codes) と一致する
#[test]
fn session_termination_codes_match_iana_registry() {
    assert_eq!(SESSION_NO_ERROR, 0x0);
    assert_eq!(SESSION_INTERNAL_ERROR, 0x1);
    assert_eq!(SESSION_UNAUTHORIZED, 0x2);
    assert_eq!(SESSION_PROTOCOL_VIOLATION, 0x3);
    assert_eq!(SESSION_INVALID_REQUEST_ID, 0x4);
    assert_eq!(SESSION_DUPLICATE_TRACK_ALIAS, 0x5);
    assert_eq!(SESSION_KEY_VALUE_FORMATTING_ERROR, 0x6);
    assert_eq!(SESSION_INVALID_PATH, 0x8);
    assert_eq!(SESSION_MALFORMED_PATH, 0x9);
    assert_eq!(SESSION_GOAWAY_TIMEOUT, 0x10);
    assert_eq!(SESSION_CONTROL_MESSAGE_TIMEOUT, 0x11);
    assert_eq!(SESSION_DATA_STREAM_TIMEOUT, 0x12);
    assert_eq!(SESSION_AUTH_TOKEN_CACHE_OVERFLOW, 0x13);
    assert_eq!(SESSION_DUPLICATE_AUTH_TOKEN_ALIAS, 0x14);
    assert_eq!(SESSION_MALFORMED_AUTH_TOKEN, 0x16);
    assert_eq!(SESSION_UNKNOWN_AUTH_TOKEN_ALIAS, 0x17);
    assert_eq!(SESSION_EXPIRED_AUTH_TOKEN, 0x18);
    assert_eq!(SESSION_INVALID_AUTHORITY, 0x19);
    assert_eq!(SESSION_MALFORMED_AUTHORITY, 0x1A);
    assert_eq!(SESSION_TOO_MANY_REQUEST_UPDATES, 0x1B);
}

/// §16.11.2 (REQUEST_ERROR Codes) と一致する
#[test]
fn request_error_codes_match_iana_registry() {
    assert_eq!(REQUEST_INTERNAL_ERROR, 0x0);
    assert_eq!(REQUEST_UNAUTHORIZED, 0x1);
    assert_eq!(REQUEST_TIMEOUT, 0x2);
    assert_eq!(REQUEST_NOT_SUPPORTED, 0x3);
    assert_eq!(REQUEST_MALFORMED_AUTH_TOKEN, 0x4);
    assert_eq!(REQUEST_EXPIRED_AUTH_TOKEN, 0x5);
    assert_eq!(REQUEST_GOING_AWAY, 0x6);
    assert_eq!(REQUEST_EXCESSIVE_LOAD, 0x9);
    assert_eq!(REQUEST_DOES_NOT_EXIST, 0x10);
    assert_eq!(REQUEST_INVALID_RANGE, 0x11);
    assert_eq!(REQUEST_MALFORMED_TRACK, 0x12);
    assert_eq!(REQUEST_UNINTERESTED, 0x20);
    assert_eq!(REQUEST_PREFIX_OVERLAP, 0x30);
    assert_eq!(REQUEST_NAMESPACE_TOO_LARGE, 0x31);
    assert_eq!(REQUEST_UNSUPPORTED_EXTENSION, 0x33);
    assert_eq!(REQUEST_REDIRECT, 0x34);
    assert_eq!(REQUEST_CONFLICTING_FILTERS, 0x35);
    assert_eq!(REQUEST_INVALID_FILTER, 0x36);
}

/// §16.11.3 (PUBLISH_DONE Codes) と一致する
#[test]
fn publish_done_codes_match_iana_registry() {
    assert_eq!(PUBLISH_DONE_INTERNAL_ERROR, 0x0);
    assert_eq!(PUBLISH_DONE_UNAUTHORIZED, 0x1);
    assert_eq!(PUBLISH_DONE_TRACK_ENDED, 0x2);
    assert_eq!(PUBLISH_DONE_GOING_AWAY, 0x4);
    assert_eq!(PUBLISH_DONE_TOO_FAR_BEHIND, 0x5);
    assert_eq!(PUBLISH_DONE_EXPIRED, 0x6);
    assert_eq!(PUBLISH_DONE_UPDATE_FAILED, 0x8);
    assert_eq!(PUBLISH_DONE_EXCESSIVE_LOAD, 0x9);
    assert_eq!(PUBLISH_DONE_MALFORMED_TRACK, 0x12);
}

/// §16.11.4 (Stream Reset Error Codes) と一致する
#[test]
fn stream_reset_codes_match_iana_registry() {
    assert_eq!(STREAM_INTERNAL_ERROR, 0x0);
    assert_eq!(STREAM_CANCELLED, 0x1);
    assert_eq!(STREAM_DELIVERY_TIMEOUT, 0x2);
    assert_eq!(STREAM_SESSION_CLOSED, 0x3);
    assert_eq!(STREAM_GOING_AWAY, 0x4);
    assert_eq!(STREAM_TOO_FAR_BEHIND, 0x5);
    assert_eq!(STREAM_UNKNOWN_OBJECT_STATUS, 0x6);
    assert_eq!(STREAM_EXPIRED_AUTH_TOKEN, 0x7);
    assert_eq!(STREAM_EXCESSIVE_LOAD, 0x9);
    assert_eq!(STREAM_MALFORMED_TRACK, 0x12);
}
